branches:
    - main
    - master
tagFormat: ${version}
preset: conventionalcommits
plugins:
    - "@semantic-release/commit-analyzer"
    - - "@semantic-release/release-notes-generator"
      - presetConfig:
            types:
                - type: "fix"
                  section: "Fixes"
                - type: "feat"
                  section: "Features"
                - type: "perf"
                  section: "Performance Improvements"
    - - "@semantic-release/changelog"
      - changelogFile: CHANGELOG.md
    - - "@semantic-release/exec"
      - prepareCmd: |
            sed -i 's/"version": "[^"]*"/"version": "${nextRelease.version}"/' manifest.json
            sed -i 's/export const VERSION = ".*"/export const VERSION = "${nextRelease.version}"/' src/version.ts
            npm version ${nextRelease.version} --no-git-tag-version
            npm run build
    - - "@semantic-release/git"
      - assets:
            - CHANGELOG.md
            - manifest.json
            - package.json
            - package-lock.json
            - src/version.ts
        message: |-
            chore(release): ${nextRelease.version} [skip ci]

            ${nextRelease.notes}
    - - "@semantic-release/github"
      - assets:
            - main.js
            - manifest.json
            - styles.css
