branches:
    - main
    - master
plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - - "@semantic-release/changelog"
      - changelogFile: CHANGELOG.md
    - - "@semantic-release/exec"
      - prepareCmd: |
            sed -i "s/\"version\": \".*\"/\"version\": \"\${nextRelease.version}\"/" manifest.json
    - - "@semantic-release/git"
      - assets:
            - CHANGELOG.md
            - manifest.json
        message: |-
            chore(release): ${nextRelease.version} [skip ci]

            ${nextRelease.notes}
    - - "@semantic-release/github"
      - assets:
            - main.js
            - manifest.json
            - styles.css
